"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Unhappiness = exports.Research = exports.Production = exports.PopulationUnhappiness = exports.MilitaryUnhappiness = exports.MartialLaw = exports.LuxuryHappiness = exports.Luxuries = exports.Happiness = exports.Gold = exports.CityImprovementContent = void 0;
var CityImprovementContent_1 = require("@civ-clone/base-city-yield-city-improvement-content/CityImprovementContent");
Object.defineProperty(exports, "CityImprovementContent", { enumerable: true, get: function () { return CityImprovementContent_1.CityImprovementContent; } });
var Yields_1 = require("@civ-clone/civ1-city/Yields");
Object.defineProperty(exports, "Gold", { enumerable: true, get: function () { return Yields_1.Gold; } });
var Happiness_1 = require("@civ-clone/base-city-yield-happiness/Happiness");
Object.defineProperty(exports, "Happiness", { enumerable: true, get: function () { return Happiness_1.Happiness; } });
var Luxuries_1 = require("@civ-clone/base-city-yield-luxuries/Luxuries");
Object.defineProperty(exports, "Luxuries", { enumerable: true, get: function () { return Luxuries_1.Luxuries; } });
var LuxuryHappiness_1 = require("@civ-clone/base-city-yield-luxury-happiness/LuxuryHappiness");
Object.defineProperty(exports, "LuxuryHappiness", { enumerable: true, get: function () { return LuxuryHappiness_1.LuxuryHappiness; } });
var MartialLaw_1 = require("@civ-clone/base-city-yield-martial-law-content/MartialLaw");
Object.defineProperty(exports, "MartialLaw", { enumerable: true, get: function () { return MartialLaw_1.MartialLaw; } });
var MilitaryUnhappiness_1 = require("@civ-clone/base-city-yield-military-unhappiness/MilitaryUnhappiness");
Object.defineProperty(exports, "MilitaryUnhappiness", { enumerable: true, get: function () { return MilitaryUnhappiness_1.MilitaryUnhappiness; } });
var PopulationUnhappiness_1 = require("@civ-clone/base-city-yield-population-unhappiness/PopulationUnhappiness");
Object.defineProperty(exports, "PopulationUnhappiness", { enumerable: true, get: function () { return PopulationUnhappiness_1.PopulationUnhappiness; } });
var Yields_2 = require("@civ-clone/civ1-world/Yields");
Object.defineProperty(exports, "Production", { enumerable: true, get: function () { return Yields_2.Production; } });
var Yields_3 = require("@civ-clone/civ1-science/Yields");
Object.defineProperty(exports, "Research", { enumerable: true, get: function () { return Yields_3.Research; } });
var Unhappiness_1 = require("@civ-clone/base-city-yield-unhappiness/Unhappiness");
Object.defineProperty(exports, "Unhappiness", { enumerable: true, get: function () { return Unhappiness_1.Unhappiness; } });
//# sourceMappingURL=Yields.js.map